### ISSUE TITLE
Support for instructor's first initial and last name 

### ISSUE THREAD

**Issue by muradakh** [Walden-Shen/uoft-profs#4]
Hey, 

I'd like to see how this integrates with UofTCourseInfo Chrome Extension. I should be able to link to your website from the instructor names in the tooltip. The only issue is my extension relies on course data provided by Cobalt API which does not provide the instructor's full name, just the first initial and last name. 

Do you think you can make this work?

Thanks!

**Comment by ZewenShen** [comment]
It’s possible but it will be a lot of work — since there must be repeated instructor abbreviation name. 

imo, it’s better to use a hash table, which accepts (department, instructor abbreviation) and returns instructor full name. Then you can use that full name to link to my service. 

And that “department” can be retrieved by using the first three letters of the course id that one teaches.

So my question is, is it possible to have (department, abbreviation) with your app?

**Comment by muradakh** [comment]
Yeah I have access to department and the abbreviation but I don't have a dataset to generate that hashmap. So I can't obtain the full instructor name at the moment. Do you by any chance have parsesble list of all instructors and their departments? Then we could probably generate a hashmap like you suggested either on your end or my end

**Comment by ZewenShen** [comment]
I do have a table which comprises instructor abbreviation name and full name and their department in my MySQL server. Shall we talk about this on messenger? It’s not that convenient to chat on github. I will add you on fb later :)

**Comment by muradakh** [comment]
The feature has been added, so closing this issue.
